"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path 
from datetime import timedelta 

REST_FRAMEWORK ={
'DEFAULT_AUTHENTICATION_CLASSES':(
'rest_framework_simplejwt.authentication.JWTAuthentication',
),
'DEFAULT_PERMISSION_CLASSES':(
'rest_framework.permissions.AllowAny',
),
'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination',
'PAGE_SIZE':10 ,
}


SIMPLE_JWT ={
'ACCESS_TOKEN_LIFETIME':timedelta (days =1 ),
'REFRESH_TOKEN_LIFETIME':timedelta (days =7 ),
'ROTATE_REFRESH_TOKENS':False ,
'BLACKLIST_AFTER_ROTATION':True ,
'AUTH_HEADER_TYPES':('Bearer',),
}


BASE_DIR =Path (__file__ ).resolve ().parent .parent 






SECRET_KEY ='django-insecure-(o^m8ky_gn)hnj*v#sh-6q0_ihd+1)g$2tat_b8tx2tebtx1#8'


DEBUG =True 

ALLOWED_HOSTS =[]




INSTALLED_APPS =[
'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'django_filters',
'rest_framework',
'corsheaders',
'store',
'api',
]

MIDDLEWARE =[
'django.middleware.security.SecurityMiddleware',
'corsheaders.middleware.CorsMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF ='core.urls'

TEMPLATES =[
{
'BACKEND':'django.template.backends.django.DjangoTemplates',
'DIRS':[BASE_DIR /'front'/'templates'],
'APP_DIRS':True ,
'OPTIONS':{
'context_processors':[
'django.template.context_processors.request',
'django.template.context_processors.media',
'django.contrib.auth.context_processors.auth',
'django.contrib.messages.context_processors.messages',
],
},
},
]

WSGI_APPLICATION ='core.wsgi.application'





DATABASES ={
'default':{
'ENGINE':'django.db.backends.sqlite3',
'NAME':BASE_DIR /'db.sqlite3',
}
}





AUTH_PASSWORD_VALIDATORS =[
{
'NAME':'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
},
{
'NAME':'django.contrib.auth.password_validation.MinimumLengthValidator',
},
{
'NAME':'django.contrib.auth.password_validation.CommonPasswordValidator',
},
{
'NAME':'django.contrib.auth.password_validation.NumericPasswordValidator',
},
]





LANGUAGE_CODE ='ru'

TIME_ZONE ='UTC'

USE_I18N =True 

USE_TZ =True 





STATICFILES_DIRS =[BASE_DIR /'front'/'static']
STATIC_URL ='/static/'
MEDIA_URL ='/media/'
MEDIA_ROOT =BASE_DIR /'media'


CORS_ALLOWED_ORIGINS =[
"http://localhost:3000",
"http://127.0.0.1:3000",
]






REST_FRAMEWORK ={
'DEFAULT_AUTHENTICATION_CLASSES':(
'rest_framework_simplejwt.authentication.JWTAuthentication',
),
'DEFAULT_PERMISSION_CLASSES':(
'rest_framework.permissions.AllowAny',
),
'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination',
'PAGE_SIZE':10 ,
}
